kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-log-pv
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gitlab-log
  hostPath:
   path: /home/volumes/gitlab/log
