kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-home-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gitlab-home
  hostPath:
   path: /home/volumes/gitlab/home
