---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-claim
  labels:
    app: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitlab-data
  resources:
    requests:
      storage: 10Gi
