---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-log-claim
  labels:
    app: gitlab-log
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitlab-log
  resources:
    requests:
      storage: 10Gi
